apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: platform-ref-multi-k8s
  annotations:
    meta.crossplane.io/maintainer: Jared Watts <jared@upbound.io>
    meta.crossplane.io/source: github.com/upbound/platform-ref-multi-k8s
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This reference platform Configuration for multi-cloud Kubernetes is a starting point to build,
      run, and operate your own internal cloud platform and offer a self-service console and API to
      your internal teams.

    meta.crossplane.io/readme: |
      This reference platform `Configuration` for multi-cloud Kubernetes is a starting point
      to build, run, and operate your own internal cloud platform and offer a self-service console
      and API to your internal teams. It provides platform APIs to provision fully configured
      Kubernetes clusters across multiple cloud providers, such as AWS, GCP, and Azure. Your app
      teams can use these platform APIs to self-service provision their own Kubernetes clusters on
      demand when they need them, all while ensuring the configuration and policy guardrails that
      you specified are also applied.

      These platform APIs are composed using the following Crossplane providers:

      * [Crossplane AWS Provider](https://doc.crds.dev/github.com/crossplane/provider-aws)
      * [Crossplane GCP Provider](https://doc.crds.dev/github.com/crossplane/provider-gcp)
      * [Crossplane Azure Provider](https://doc.crds.dev/github.com/crossplane/provider-azure)

      App deployments can securely connect to the infrastructure they need using secrets distributed
      directly to the app namespace.

      [Quickstart Guide](https://github.com/upbound/platform-ref-multi-k8s/#quick-start)

      [APIs in this
      Configuration](https://github.com/upbound/platform-ref-multi-k8s/#apis-in-this-configuration)

      To learn more checkout the [GitHub repo](https://github.com/upbound/platform-ref-multi-k8s/)
      that you can copy and customize to meet the exact needs of your organization!

    meta.crossplane.io/iconURI: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB3aWR0aD0iNjUiIGhlaWdodD0iNjUiPjxkZWZzPjxyZWN0IGlkPSJhIiB3aWR0aD0iNjUiIGhlaWdodD0iNjUiIHg9IjAiIHk9IjAiIHJ4PSIxNiIvPjwvZGVmcz48ZyBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPjxtYXNrIGlkPSJiIiBmaWxsPSIjZmZmIj48dXNlIHhsaW5rOmhyZWY9IiNhIi8+PC9tYXNrPjx1c2UgZmlsbD0iIzY2NTFDQyIgZmlsbC1ydWxlPSJub256ZXJvIiB4bGluazpocmVmPSIjYSIvPjxnIG1hc2s9InVybCgjYikiPjxwYXRoIGZpbGw9IiM5MjcxRjMiIGZpbGwtb3BhY2l0eT0iLjY4IiBkPSJNMzUuMDgzNDg5MTEgMzAuMzM0MjE4NTdsMTIuMzM5MTAxMzEgNi42MzgwNzA4MmMxLjk0NTQ4MTg1IDEuMDQ2NjExNTkgMi42NzQxNjAwNyAzLjQ3MjE4MjQ4IDEuNjI3NTQ4NTMgNS40MTc2NjQyNC0uMzQ1MDI3MzcuNjQxMzUwMTQtLjg1ODYwMjA2IDEuMTc2MzM1Mi0xLjQ4NTMzMzQzIDEuNTQ3MjU1MTdsLTEyLjYzMTExMjg2IDcuNDc1NTA0MjNjLTEuMjAxMjg1NTguNzEwOTU5ODctMi42ODYzMTE3MS43NDQyNDg3OC0zLjkxODI0ODkyLjA4NzgzMjhsLTEyLjQ1MzExNTI1LTYuNjM1NDIyN2MtMS45NDk2NDU2OS0xLjAzODgzNDM1LTIuNjg4MDA0MjItMy40NjE0NzYwNi0xLjY0OTE2OTktNS40MTExMjE4LjM0NzQyNjYtLjY1MjAzNzM0Ljg2ODY1MzQ2LTEuMTk1MTExOSAxLjUwNTg4Mzc2LTEuNTY5MDA0MjNsMTIuNzQ1MTI2ODUtNy40NzgxNTIzMWMxLjIwNDIyODk1LS43MDY1NzY1MyAyLjY4OTc0MDU4LS43MzQxMDM1NCAzLjkxOTMxOTkxLS4wNzI2MjYyMnoiLz48cGF0aCBmaWxsPSIjOUE4N0ZGIiBkPSJNMzUuMDgzNDg5MjYgMjIuMTA3NzYwMzFsMTIuMzM5MTAxMjYgNi42MzgwNzA5YzEuOTQ1NDgxODUgMS4wNDY2MTE2IDIuNjc0MTYwMDcgMy40NzIxODI0OSAxLjYyNzU0ODUzIDUuNDE3NjY0MjUtLjM0NTAyNzMyLjY0MTM1MDA1LS44NTg2MDIwNiAxLjE3NjMzNTItMS40ODUzMzM0MyAxLjU0NzI1NTE3bC0xMi42MzExMTI4IDcuNDc1NTA0MTRjLTEuMjAxMjg1NjQuNzEwOTU5OTYtMi42ODYzMTE3Ny43NDQyNDg4Ni0zLjkxODI0ODkzLjA4NzgzMjgxbC0xMi40NTMxMTUyNS02LjYzNTQyMjdjLTEuOTQ5NjQ1NzQtMS4wMzg4MzQyOC0yLjY4ODAwNDI3LTMuNDYxNDc1OTktMS42NDkxNjk5NC01LjQxMTEyMTcyLjM0NzQyNjU5LS42NTIwMzczNS44Njg2NTM0NS0xLjE5NTExMTkxIDEuNTA1ODgzNzUtMS41NjkwMDQyM0wzMS4xNjQxNjkzIDIyLjE4MDM4NjZjMS4yMDQyMjg5NS0uNzA2NTc2NTIgMi42ODk3NDA1OC0uNzM0MTAzNTMgMy45MTkzMTk5Ni0uMDcyNjI2M3oiLz48cGF0aCBmaWxsPSIjRDZCN0ZGIiBkPSJNMzUuMDgzNDg5MyAxNC41OTE2MTYyNWwxMi4zMzkxMDEyNyA2LjYzODA3MDg4YzEuOTQ1NDgxODUgMS4wNDY2MTE1OSAyLjY3NDE2MDA5IDMuNDcyMTgyNDUgMS42Mjc1NDg1MyA1LjQxNzY2NDI0LS4zNDUwMjczMi42NDEzNTAwNi0uODU4NjAyMDYgMS4xNzYzMzUyLTEuNDg1MzMzNDMgMS41NDcyNTUxN2wtMTIuNjMxMTEyOCA3LjQ3NTUwNDE1Yy0xLjIwMTI4NTY0LjcxMDk1OTk1LTIuNjg2MzExNzcuNzQ0MjQ4ODYtMy45MTgyNDg5My4wODc4MzI4TDE4LjU2MjMyODcgMjkuMTIyNTIwOGMtMS45NDk2NDU3NC0xLjAzODgzNDI3LTIuNjg4MDA0MjctMy40NjE0NzU5OC0xLjY0OTE2OTk0LTUuNDExMTIxNzIuMzQ3NDI2NTktLjY1MjAzNzM0Ljg2ODY1MzQ1LTEuMTk1MTExOSAxLjUwNTg4Mzc1LTEuNTY5MDA0MjNsMTIuNzQ1MTI2ODgtNy40NzgxNTIzNmMxLjIwNDIyODkyLS43MDY1NzY0OCAyLjY4OTc0MDU1LS43MzQxMDM1IDMuOTE5MzE5OTItLjA3MjYyNjIzeiIvPjwvZz48L2c+PC9zdmc+

    friendly-name.meta.crossplane.io: Multi-cloud Kubernetes
    friendly-group-name.meta.crossplane.io/multik8s.platformref.crossplane.io: Kubernetes

    friendly-kind-name.meta.crossplane.io/compositenetwork.multik8s.platformref.crossplane.io: Composite Network
    friendly-kind-name.meta.crossplane.io/network.multik8s.platformref.crossplane.io: Network

    friendly-kind-name.meta.crossplane.io/compositecluster.multik8s.platformref.crossplane.io: Composite Kubernetes Cluster
    friendly-kind-name.meta.crossplane.io/cluster.multik8s.platformref.crossplane.io: Kubernetes Cluster

    friendly-kind-name.meta.crossplane.io/services.aws.platformref.crossplane.io: Cluster Services
    friendly-kind-name.meta.crossplane.io/eks.multik8s.platformref.crossplane.io: EKS Cluster
    friendly-kind-name.meta.crossplane.io/gke.multik8s.platformref.crossplane.io: GKE Cluster

    # TODO(negz): Remove these older style annotations once annotation consumers
    # have had a chance to update.
    company: Upbound
    maintainer: Jared Watts <jared@upbound.io>
    keywords: aws, gcp, azure, cloud-native, kubernetes, example, platform, reference
    source: github.com/upbound/platform-ref-multi-k8s
    license: Apache-2.0
    descriptionShort: |
      The reference platform for multi-cloud Kubernetes instances.

    description: |
      This reference platform Configuration for multi-cloud Kubernetes is a starting point to build,
      run, and operate your own internal cloud platform and offer a self-service console and API to
      your internal teams.

    readme: |
      This reference platform `Configuration` for multi-cloud Kubernetes is a starting point
      to build, run, and operate your own internal cloud platform and offer a self-service console
      and API to your internal teams. It provides platform APIs to provision fully configured
      Kubernetes clusters across multiple cloud providers, such as AWS, GCP, and Azure. Your app
      teams can use these platform APIs to self-service provision their own Kubernetes clusters on
      demand when they need them, all while ensuring the configuration and policy guardrails that
      you specified are also applied.

      These platform APIs are composed using the following Crossplane providers:

      * [Crossplane AWS Provider](https://doc.crds.dev/github.com/crossplane/provider-aws)
      * [Crossplane GCP Provider](https://doc.crds.dev/github.com/crossplane/provider-gcp)
      * [Crossplane Azure Provider](https://doc.crds.dev/github.com/crossplane/provider-azure)

      App deployments can securely connect to the infrastructure they need using secrets distributed
      directly to the app namespace.

      [Quickstart Guide](https://github.com/upbound/platform-ref-multi-k8s/#quick-start)

      [APIs in this
      Configuration](https://github.com/upbound/platform-ref-multi-k8s/#apis-in-this-configuration)

      To learn more checkout the [GitHub repo](https://github.com/upbound/platform-ref-multi-k8s/)
      that you can copy and customize to meet the exact needs of your organization!

    iconData: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB3aWR0aD0iNjUiIGhlaWdodD0iNjUiPjxkZWZzPjxyZWN0IGlkPSJhIiB3aWR0aD0iNjUiIGhlaWdodD0iNjUiIHg9IjAiIHk9IjAiIHJ4PSIxNiIvPjwvZGVmcz48ZyBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPjxtYXNrIGlkPSJiIiBmaWxsPSIjZmZmIj48dXNlIHhsaW5rOmhyZWY9IiNhIi8+PC9tYXNrPjx1c2UgZmlsbD0iIzY2NTFDQyIgZmlsbC1ydWxlPSJub256ZXJvIiB4bGluazpocmVmPSIjYSIvPjxnIG1hc2s9InVybCgjYikiPjxwYXRoIGZpbGw9IiM5MjcxRjMiIGZpbGwtb3BhY2l0eT0iLjY4IiBkPSJNMzUuMDgzNDg5MTEgMzAuMzM0MjE4NTdsMTIuMzM5MTAxMzEgNi42MzgwNzA4MmMxLjk0NTQ4MTg1IDEuMDQ2NjExNTkgMi42NzQxNjAwNyAzLjQ3MjE4MjQ4IDEuNjI3NTQ4NTMgNS40MTc2NjQyNC0uMzQ1MDI3MzcuNjQxMzUwMTQtLjg1ODYwMjA2IDEuMTc2MzM1Mi0xLjQ4NTMzMzQzIDEuNTQ3MjU1MTdsLTEyLjYzMTExMjg2IDcuNDc1NTA0MjNjLTEuMjAxMjg1NTguNzEwOTU5ODctMi42ODYzMTE3MS43NDQyNDg3OC0zLjkxODI0ODkyLjA4NzgzMjhsLTEyLjQ1MzExNTI1LTYuNjM1NDIyN2MtMS45NDk2NDU2OS0xLjAzODgzNDM1LTIuNjg4MDA0MjItMy40NjE0NzYwNi0xLjY0OTE2OTktNS40MTExMjE4LjM0NzQyNjYtLjY1MjAzNzM0Ljg2ODY1MzQ2LTEuMTk1MTExOSAxLjUwNTg4Mzc2LTEuNTY5MDA0MjNsMTIuNzQ1MTI2ODUtNy40NzgxNTIzMWMxLjIwNDIyODk1LS43MDY1NzY1MyAyLjY4OTc0MDU4LS43MzQxMDM1NCAzLjkxOTMxOTkxLS4wNzI2MjYyMnoiLz48cGF0aCBmaWxsPSIjOUE4N0ZGIiBkPSJNMzUuMDgzNDg5MjYgMjIuMTA3NzYwMzFsMTIuMzM5MTAxMjYgNi42MzgwNzA5YzEuOTQ1NDgxODUgMS4wNDY2MTE2IDIuNjc0MTYwMDcgMy40NzIxODI0OSAxLjYyNzU0ODUzIDUuNDE3NjY0MjUtLjM0NTAyNzMyLjY0MTM1MDA1LS44NTg2MDIwNiAxLjE3NjMzNTItMS40ODUzMzM0MyAxLjU0NzI1NTE3bC0xMi42MzExMTI4IDcuNDc1NTA0MTRjLTEuMjAxMjg1NjQuNzEwOTU5OTYtMi42ODYzMTE3Ny43NDQyNDg4Ni0zLjkxODI0ODkzLjA4NzgzMjgxbC0xMi40NTMxMTUyNS02LjYzNTQyMjdjLTEuOTQ5NjQ1NzQtMS4wMzg4MzQyOC0yLjY4ODAwNDI3LTMuNDYxNDc1OTktMS42NDkxNjk5NC01LjQxMTEyMTcyLjM0NzQyNjU5LS42NTIwMzczNS44Njg2NTM0NS0xLjE5NTExMTkxIDEuNTA1ODgzNzUtMS41NjkwMDQyM0wzMS4xNjQxNjkzIDIyLjE4MDM4NjZjMS4yMDQyMjg5NS0uNzA2NTc2NTIgMi42ODk3NDA1OC0uNzM0MTAzNTMgMy45MTkzMTk5Ni0uMDcyNjI2M3oiLz48cGF0aCBmaWxsPSIjRDZCN0ZGIiBkPSJNMzUuMDgzNDg5MyAxNC41OTE2MTYyNWwxMi4zMzkxMDEyNyA2LjYzODA3MDg4YzEuOTQ1NDgxODUgMS4wNDY2MTE1OSAyLjY3NDE2MDA5IDMuNDcyMTgyNDUgMS42Mjc1NDg1MyA1LjQxNzY2NDI0LS4zNDUwMjczMi42NDEzNTAwNi0uODU4NjAyMDYgMS4xNzYzMzUyLTEuNDg1MzMzNDMgMS41NDcyNTUxN2wtMTIuNjMxMTEyOCA3LjQ3NTUwNDE1Yy0xLjIwMTI4NTY0LjcxMDk1OTk1LTIuNjg2MzExNzcuNzQ0MjQ4ODYtMy45MTgyNDg5My4wODc4MzI4TDE4LjU2MjMyODcgMjkuMTIyNTIwOGMtMS45NDk2NDU3NC0xLjAzODgzNDI3LTIuNjg4MDA0MjctMy40NjE0NzU5OC0xLjY0OTE2OTk0LTUuNDExMTIxNzIuMzQ3NDI2NTktLjY1MjAzNzM0Ljg2ODY1MzQ1LTEuMTk1MTExOSAxLjUwNTg4Mzc1LTEuNTY5MDA0MjNsMTIuNzQ1MTI2ODgtNy40NzgxNTIzNmMxLjIwNDIyODkyLS43MDY1NzY0OCAyLjY4OTc0MDU1LS43MzQxMDM1IDMuOTE5MzE5OTItLjA3MjYyNjIzeiIvPjwvZz48L2c+PC9zdmc+
spec:
  crossplane:
    version: ">=v1.0.0-0"
  dependsOn:
    - provider: registry.upbound.io/crossplane/provider-aws
      version: ">=v0.22.0-0"
    - provider: registry.upbound.io/crossplane/provider-gcp
      version: ">=v0.18.0-0"
    - provider: registry.upbound.io/crossplane/provider-helm
      version: ">=v0.9.0-0"
