apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    secretRef:
      key: credentials.json
      name: gcp-credentials
      namespace: crossplane-system
    source: Secret
  projectID: crossplane-playground
