apiVersion: multik8s.platformref.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: platform-ref-m-k8s-gcp
  namespace: default
spec:
  compositeDeletePolicy: Foreground
  parameters:
    cloud: gcp
    id: platform-ref-m-k8s-gcp
    region: us-west2
    version: latest
    nodes:
      count: 3
      instanceType: n1-standard-4
    gitops:
      git:
        url: https://github.com/upbound/platform-ref-multi-k8s/
        ref:
          # refs/heads/main
          # refs/tags/v0.1.0
          # refs/pull/420/head
          # refs/merge-requests/1/head
          name: refs/heads/main
  writeConnectionSecretToRef:
    name: platform-ref-m-k8s-gcp-kubeconfig